/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import static design.addcontact.List;
import static design.addcontact.addContact;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asus
 */
public class Editing_Page extends javax.swing.JFrame {

    /**
     * Creates new form Editing_Page
     */
    public Editing_Page() {
        initComponents();
        Set_Details();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        namefield = new javax.swing.JTextField();
        numfield = new javax.swing.JTextField();
        mailfield = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        notes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Save_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        namefield.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        namefield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        namefield.setBorder(null);
        jPanel1.add(namefield);
        namefield.setBounds(348, 65, 360, 80);

        numfield.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        numfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numfieldActionPerformed(evt);
            }
        });
        jPanel1.add(numfield);
        numfield.setBounds(170, 290, 280, 32);

        mailfield.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mailfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(mailfield);
        mailfield.setBounds(170, 390, 280, 34);

        jTextField4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(170, 440, 280, 32);

        birthday.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayActionPerformed(evt);
            }
        });
        jPanel1.add(birthday);
        birthday.setBounds(170, 490, 280, 35);

        address.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(address);
        address.setBounds(170, 340, 280, 37);

        notes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        notes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(notes);
        notes.setBounds(170, 540, 270, 36);

        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(41, 25, 200, 200);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setText("Upload New Photo");
        jPanel1.add(jButton1);
        jButton1.setBounds(46, 243, 190, 25);

        Save_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Save_Button.setText("Save");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Save_Button);
        Save_Button.setBounds(520, 510, 100, 50);

        Back_Button.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Button);
        Back_Button.setBounds(655, 510, 90, 50);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mail");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(35, 389, 80, 20);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(24, 300, 100, 19);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Birthday");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(31, 494, 70, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 350, 70, 19);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Note");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(43, 550, 50, 19);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Group");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(34, 444, 70, 20);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/asset/EDIT_BG_BG.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 780, 580);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void Set_Details()
    {
        String fileToOpen ="G:\\PhonebookProject1\\"+ Show_Friends.What_To_View+".txt";

        try {

            FileInputStream fi = new FileInputStream(new File(fileToOpen));
            ObjectInputStream oi = new ObjectInputStream(fi);

            // Read objects
            Users1 ob1 = (Users1) oi.readObject();
            namefield.setText(ob1.name);
            numfield.setText(ob1.phone);
            mailfield.setText(ob1.group);
            //.setText(ob1.email);
            birthday.setText(ob1.birthday_month);
            address.setText(ob1.adress);
            notes.setText(ob1.note);    

            oi.close();
            fi.close();

        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        }catch (IOException e) {
            System.out.println("Error initializing stream");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        // TODO add your handling code here:
         Users1 ob1 = new Users1();
        ob1.name = namefield.getText();
        //New_Name = namefield.getText();
        //New_Name=ob1.name;
        ob1.phone = numfield.getText();
        ob1.email = mailfield.getText();
        /*ob1.group = groupbox.getText();
        if (ob1.group == "FAMILY") {
            FAMILY.add(namefield.getText());
        } else {
            if (ob1.group == "FRIENDS") {
                FRIENDS.add(namefield.getText());
            } else {
                WORK.add(namefield.getText());
            }
        }*/
        ob1.birthday_month = birthday.getText();
        ob1.adress = address.getText();
        ob1.note = notes.getText();
        
        File file = new File("G:\\PhonebookProject1\\" + ob1.name + ".txt");
        file.delete();
        addcontact.List.remove(namefield.getText());
         /*   if (groupbox.getText() == "FAMILY") {
                addcontact.FAMILY.remove(namefield.getText());
            } else {
                if (mailfield.getText() == "FRIENDS") {
                    addcontact.FRIENDS.remove(namefield.getText());
                } else {
                    addcontact.WORK.remove(namefield.getText());
                }
            }  
        */

        String fileName = "G:\\PhonebookProject1\\" + ob1.name + ".txt";
        File fileToOpen = new File(fileName); //creating a file
        addContact.add(ob1);
        List.add(namefield.getText());
        try {
            FileOutputStream f = new FileOutputStream(new File(fileName));
            ObjectOutputStream o = new ObjectOutputStream(f);

            // Write objects to file
            o.writeObject(ob1);
            //o.writeObject(p2);

            o.close();
            f.close();

        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        } catch (IOException e) {
            System.out.println("Error initializing stream");
        }
    }//GEN-LAST:event_Save_ButtonActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed

        // TODO add your handling code here:
        Show_Contact_List obj= new Show_Contact_List();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void numfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numfieldActionPerformed

    private void birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editing_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editing_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthday;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField mailfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField notes;
    private javax.swing.JTextField numfield;
    // End of variables declaration//GEN-END:variables
}
