/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import javax.swing.DefaultListModel;

/**
 *
 * @author Asus
 */
public class Show_Friends extends javax.swing.JFrame {

    /**
     * Creates new form Show_Friends
     */
    public Show_Friends() {
        initComponents();
        Show_Friend_List();
    }

    void Show_Friend_List()
    {
        DefaultListModel model1 = new DefaultListModel();
        char Initial=addcontact.FRIENDS.get(0).charAt(0);
        model1.addElement(Initial);
        for (int i = 0; i < addcontact.FRIENDS.size(); i++) //
        {
            if(Initial==addcontact.FRIENDS.get(i).charAt(0))
            model1.addElement(addcontact.FRIENDS.get(i));
            else{
                Initial=addcontact.FRIENDS.get(i).charAt(0);
                model1.addElement(" ");
                model1.addElement(Initial);
                model1.addElement(addcontact.FRIENDS.get(i));
            }
        }
        jList1.setModel(model1); 
       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Details_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        Background_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        Details_Button.setText("Show Details");
        Details_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Details_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Details_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        Background_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/asset/SchoolchildrenGroup.jpg"))); // NOI18N
        getContentPane().add(Background_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 0, 494, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        // TODO add your handling code here:
        HOMENU obj = new HOMENU();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    public static String What_To_View;
    
    private void Details_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Details_ButtonActionPerformed
        // TODO add your handling code here:
        What_To_View=jList1.getSelectedValue();
        Show_Details obj= new Show_Details();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Details_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_Friends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel Background_Label;
    private javax.swing.JButton Details_Button;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
