package design;

import static design.Show_Friends.What_To_View;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

public class Show_Contact_List extends javax.swing.JFrame {

    public Show_Contact_List() {
        initComponents();
        
        Show_List();
        
        
        
        //addRowToJTable();
        //jTextField1.setText("hello");

        //jTextField1.setText(addcontact.Get_New_Contact());
        //jTextField1.setText(addcontact.addContact.get(0).name);
        //jTextField1.setText(addcontact.List.get(0));
    }
    
    void Show_List()
    {
        DefaultListModel model1 = new DefaultListModel();
        Collections.sort(addcontact.List);
             BufferedWriter out = null;
        try {
            // TODO add your handling code here:
            
              out = new BufferedWriter(new FileWriter("Show_Contact_List.txt"));
            for (int i = 0; i < addcontact.List.size(); i++) {
                out.write((String) addcontact.List.get(i));
                out.newLine();
                //fw.write((String) aList.get(i));
            }   out.close();
        } catch (IOException ex) {
            Logger.getLogger(Show_Details.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(Show_Details.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        char Initial=addcontact.List.get(0).charAt(0);
        model1.addElement(Initial);
        for (int i = 0; i < addcontact.List.size(); i++) //
        {
            if(Initial==addcontact.List.get(i).charAt(0))
            model1.addElement(addcontact.List.get(i));
            else{
                Initial=addcontact.List.get(i).charAt(0);
                model1.addElement(" ");
                model1.addElement(Initial);
                model1.addElement(addcontact.List.get(i));
            }
        }
        jList1.setModel(model1);
    }

    public void addRowToJTable() {
        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //ArrayList<User> list=Users();
        Object rowData[] = new Object[4];
        for (int i = 0; i < addcontact.addContact.size(); i++) //rowData[i]=addcontact.addContact.get(i).name;
        /*
        for(int i=0;i<list.size();i++){
            rowData[0]=list.get(i).id;
            rowData[1]=list.get(i).fname;
            rowData[2]=list.get(i).lname;
            rowData[3]=list.get(i).age;
            model.addRow(rowData);
        }
         */ {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Back_Button = new javax.swing.JButton();
        Show_Details_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setBackground(new java.awt.Color(255, 255, 204));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jList1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jList1);

        Back_Button.setText("BACK");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        Show_Details_Button.setText("Show Details");
        Show_Details_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_Details_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Show_Details_Button)
                    .addComponent(Back_Button))
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 253, Short.MAX_VALUE)
                .addComponent(Show_Details_Button)
                .addGap(52, 52, 52)
                .addComponent(Back_Button)
                .addGap(138, 138, 138))
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        // TODO add your handling code here:
        HOMENU obj = new HOMENU();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Show_Details_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_Details_ButtonActionPerformed
        // TODO add your handling code here:
        What_To_View=jList1.getSelectedValue();
        Show_Details obj= new Show_Details();
        obj.setVisible(true);
        this.setVisible(false);
        System.out.println(What_To_View);
    }//GEN-LAST:event_Show_Details_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_Contact_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_Contact_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_Contact_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_Contact_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_Contact_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Show_Details_Button;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
