/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import static design.addcontact.FAMILY;
import static design.addcontact.FRIENDS;
import static design.addcontact.List;
import static design.addcontact.WORK;
import static design.addcontact.addContact;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */
public class Show_Details extends javax.swing.JFrame {

    /**
     * Creates new form Show_Details
     */
    public Show_Details() {
        initComponents();
        //Show_Name.setText("Mor ga");
        //jTextArea1.setText("Mor ga");
        //jLabel1.setName("Mor ga");

        String demo = Show_Friends.What_To_View;
        String fileToOpen = "G:\\PhonebookProject1\\" + demo + ".txt";

        try {

            FileInputStream fi = new FileInputStream(new File(fileToOpen));
            ObjectInputStream oi = new ObjectInputStream(fi);

            // Read objects
            Users1 ob1 = (Users1) oi.readObject();
            namefield.setText(ob1.name);
            numfield.setText(ob1.phone);
            mailfield.setText(ob1.email);
            groupbox.setText(ob1.group);
            birthday.setText(ob1.birthday_day+ob1.birthday_month);
            address.setText(ob1.adress);
            notes.setText(ob1.note);

            Photo_Label.setIcon(new ImageIcon("G:\\Photo\\" + demo + ".jpg"));

            oi.close();
            fi.close();

        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        } catch (IOException e) {
            System.out.println("Error initializing stream");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Photo_Label = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        numfield = new javax.swing.JTextField();
        mailfield = new javax.swing.JTextField();
        groupbox = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        notes = new javax.swing.JTextField();
        Edit_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        Back_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        jPanel1.add(Photo_Label);
        Photo_Label.setBounds(0, 558, 200, 200);

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        jPanel1.add(namefield);
        namefield.setBounds(81, 66, 144, 26);
        jPanel1.add(numfield);
        numfield.setBounds(115, 124, 110, 26);
        jPanel1.add(mailfield);
        mailfield.setBounds(230, 410, 116, 26);
        jPanel1.add(groupbox);
        groupbox.setBounds(510, 420, 183, 26);
        jPanel1.add(birthday);
        birthday.setBounds(206, 530, 160, 26);
        jPanel1.add(address);
        address.setBounds(230, 470, 137, 26);
        jPanel1.add(notes);
        notes.setBounds(470, 470, 153, 26);

        Edit_Button.setText("EDIT");
        Edit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_Button);
        Edit_Button.setBounds(589, 159, 69, 29);

        Delete_Button.setText("DELETE");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Delete_Button);
        Delete_Button.setBounds(580, 353, 89, 29);

        Back_Button.setText("BACK");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Button);
        Back_Button.setBounds(589, 256, 71, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\SD\\final\\final\\final\\src\\resources\\asset\\BGWHITE.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        // TODO add your handling code here:
        HOMENU obj = new HOMENU();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    
    
    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        BufferedWriter out = null;
        try {
            // TODO add your handling code here:
            addcontact.List.remove(namefield.getText());
            if (groupbox.getText() == "FAMILY") {
                addcontact.FAMILY.remove(namefield.getText());
            } else {
                if (groupbox.getText() == "FRIENDS") {
                    addcontact.FRIENDS.remove(namefield.getText());
                } else {
                    addcontact.WORK.remove(namefield.getText());
                }
            }   out = new BufferedWriter(new FileWriter("Show_Contact_List.txt"));
            for (int i = 0; i < addcontact.List.size(); i++) {
                out.write((String) addcontact.List.get(i));
                out.newLine();
                //fw.write((String) aList.get(i));
            }   out.close();
        } catch (IOException ex) {
            Logger.getLogger(Show_Details.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                out.close();
            } catch (IOException ex) {
                Logger.getLogger(Show_Details.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        File file = new File("G:\\PhonebookProject1\\" + namefield.getText() + ".txt");
        file.delete();
    }//GEN-LAST:event_Delete_ButtonActionPerformed


    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void Edit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_ButtonActionPerformed
        // TODO add your handling code here:
        
        Editing_Page obj =new Editing_Page();
        obj.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_Edit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Edit_Button;
    private javax.swing.JLabel Photo_Label;
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthday;
    private javax.swing.JTextField groupbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mailfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField notes;
    private javax.swing.JTextField numfield;
    // End of variables declaration//GEN-END:variables
}
